### ISSUE TITLE
Cannot proceed at contact mass delete confirmation screen

### ISSUE THREAD

**Issue by noah44444** [tracmor/tracmor#49]
1) Create a company called Test Inc
2) Create a shipment including the company Test Inc.
3) Using the mass delete check box and delete button attempt to delete Test Inc.
4) A white popup will ask you to confirm "There is 1 company that is not able to be deleted. Would you like to continue the deletion process, skipping these item?" and clicking on Confirm does nothing but canceling will allow you to close the window. Clicking on Confirm should close the window instead of having to click on cancel.

**Comment by ianlinkcd** [comment]
Hi, don't comment out the check, just add this line

 protected function btnMassDeleteConfirm_Click() {
                        $items = $this->ctlSearchMenu->dtgAsset->getSelected('AssetId');

                        $this->lblWarning->Text = "";
                        // TODO perform validate
                        // Get an instance of the database
                        $objDatabase = QApplication::$Database[1];

                        /////ADD THIS LINE//////
                        // initialize and default to false.
                        $blnError = false;
                        ////////////////////////////////////
                        foreach ($items as $item) {
                        // the rest of the code...


If nothing went wrong the variable was never created, and some weird behavior was going on with
if( !$blnError )
because blnError was undefined
