### ISSUE TITLE
Mass Edit of Models is not working

### ISSUE THREAD

**Issue by pboe** [tracmor/tracmor#77]
Steps to reproduce:
1. Perform a model search
2. activate check-box of some of the models
3. click mass edit button
4. activate check-box manufaturer and chose a manufacturer
5. click apply

An error occurs:
An error occurred during AJAX Response parsing.
The error response will appear in a new popup.

Popup:
undefined is not an object (evaluating 'objErrorWindow.focus')
on line number undefined
in file undefined

**Comment by ianlinkcd** [comment]
You can fix it by adding to line 184 in to tracmor/assets/asset_list.php like below 
177         protected function btnMassDeleteConfirm_Click() {
178             $items = $this->ctlSearchMenu->dtgAsset->getSelected('AssetId');
179 
180             $this->lblWarning->Text = "";
181             // TODO perform validate
182             // Get an instance of the database
183             $objDatabase = QApplication::$Database[1];
184             $blnError = false;
185             foreach ($items as $item) {
