### ISSUE TITLE
Losing connection to MYSQL when executing source ./data_model/create.sql

### ISSUE THREAD

**Issue by rp-tech** [tracmor/tracmor#80]
Hi, I am having an issue trying to install tracmor.

When I try to execute the ./data_model/create.sql file, I am getting the following error which crashes mariadb (mysql) completely:

“ERROR 2013 (HY000): Lost connection to MySQL server during query”

I have tried numerous options to adjust mariadb accordingly, including setting the timeout values and max packet size variables but each time the query fails.

I am running 3 other php/mysql webapps on this server under apache2 and none of them have this problem. I can only assume at this point there is some compatibility problem between maria-db and Tracmor's install script.

Please help if possible, thanks!

**Comment by romcart** [comment]
Most likely the culprit can be found in your mysql error log. You may also find answers here: http://stackoverflow.com/search?q=ERROR+2013+%28HY000%29%3A+Lost+connection+to+MySQL+server+during+query
