### ISSUE TITLE
Error when logging out

### ISSUE THREAD

**Issue by Ernest-Darmanin** [tracmor/tracmor#90]
Hi,

Everything is working fine in Tracmor except from when I try to sign out. When I sign out, the following error is popping up:

dir(/tmp,/tmp): The system cannot find the file specified. (code: 2)
Error Type:   E_WARNING	

Rendered Page:   Click here to view contents able to be rendered 

Source File:   C:\xampp\htdocs\tracmor\includes\qcodo\_core\qform_state_handlers\QFileFormStateHandler.class.php	    Line:   70	

Line 65:    
Line 66:    			$strPrefix = self::$FileNamePrefix . $strSessionId;
Line 67:    
Line 68:    			// Go through all the files
Line 69:    			if (strlen($strSessionId)) {
Line 70:    				$objDirectory = dir(self::$StatePath);
Line 71:    				while (($strFile = $objDirectory->read()) !== false) {
Line 72:    					$intPosition = strpos($strFile, $strPrefix);
Line 73:    					if (($intPosition !== false) && ($intPosition == 0))
Line 74:    						unlink(sprintf('%s/%s', self::$StatePath, $strFile));
Line 75:    				}

There was a post with a similar problem and the suggestion was to:

"set a different path for storing the formstate in /includes/prepend.inc.php:

QFileFormStateHandler::$StatePath = "YOUR PATH"; "

When I tried to do this I did not find "QFileFormStateHandler" anywhere in the php file. 

I also tried to insert the command myself with the path of where tracmor is installed but it did not work.

I am installing Tracmor on a Windows Machine. 

Thanks in advanced for your help.

**Comment by Ernest-Darmanin** [comment]
Ok solved it.. 

In the  
QFileFormStateHandler.class.php     under  
class QFileFormStateHandler extends QBaseClass{  there is a variable were it sets the $StatePath.

Originally in the file the StatePath is set as follow:
public static $StatePath = '/tmp';

What I did is changed the path to:
public static $StatePath = 'C:/xampp/htdocs/tracmor/tmp'; therefore giving the full path of were my tmp folder is located and it worked.

If this is not correct please do comment else if anyone has a similar problem try this solution.

Keep up the good work TRACMOR. :D

**Comment by jaws44** [comment]
This helped me. Thanks!
